---
title: "conditions_creation"
author: "Nico"
date: "October 24, 2017"
output: html_document
---

```{r}
# Clean enviroment
rm(list = ls(all=TRUE))
```


```{r}
# Packages
if (!require('pacman')) install.packages('pacman'); library('pacman')
p_load(tidyverse)
```

# Items + pregunta

## Items
```{r}
# read text file with item
  # file name
  item_file_name <- "materials/Items/item.txt"
  # read item
  text_item <- readChar(con = item_file_name, nchars = file.info(item_file_name)$size)

# visualize item with line breaks
cat(text_item)
```

## Pregunta

```{r}
# read text file with PPV question
  # file name
  ppv_question_file_name <- "materials/Question/ppv_question.txt"
  # read question
  ppv_question <- readChar(con = ppv_question_file_name, nchars = file.info(ppv_question_file_name)$size)

# visualize item with line breaks
cat(ppv_question)

```

## Items + pregunta
```{r}
# combine item and question
problems <- paste0(text_item, "\n", ppv_question)

problems %>% cat
```

# Numbers sets
```{r}
# read csv with number
numbers_item <- read_csv("materials/Numbers/numbers_bayes.csv", col_types = cols(), skip = 1,
                         # col names
                         col_names = c("context", "ppv","multiplicator","prevalence_1", "prevalence_2", 
                                       "hit_rate_1","hit_rate_2", "false_positive_1","false_positive_2",
                                       "correct_ppv","prevalence_percentage","hit_rate_percentage",
                                       "false_positive_percentage","algorithm_hitrate_falsepositive",
                                       "algorithm_hitrate_prevalence_1", "algorithm_hitrate_prevalence_2"))
numbers_item

```

# Create items

## Inputs
```{r}

# text fields to be replaced
field_to_replace <- c("prev_1", "prev_2", "hit_rate_1", "hit_rate_2", "false_positive_1", "false_positive_2")

# replacements for text fields
field_replaces <- c(paste0(numbers_item$prevalence_1[1]), paste0(numbers_item$prevalence_2[1])
                    , paste0(numbers_item$hit_rate_1[1]), paste0(numbers_item$hit_rate_2[1])
                    , paste0(numbers_item$false_positive_1[1]), paste0(numbers_item$false_positive_2[1]))

# create frame with field to be replaced and replacements
numbers_to_text <- tibble("field_to_replace" = field_to_replace, "field_replaces" = field_replaces)


```

## Create items (combine items with numbers)
```{r}

item_xxx <- problems

# create item
for (i in 1:nrow(numbers_to_text)){
  
  # i=2
  
  item_xxx =
    gsub(numbers_to_text$field_to_replace[i], numbers_to_text$field_replaces[i], item_xxx)

}

# final item
cat(item_xxx)
```

# Respuesta

```{r}
# global-systematic
  # ____%

glob_systematic <- "____%"

# global-intuitive
  # muy baja, baja, intermedia, alta, muy alta

glob_intuitive <- "Muy baja     Baja      Intermedia      Alta      Muy alta"

# sequential-simple
  # ____ de cada ____

seq_simple <- "_____ de cada _____"

# sequential-guided
  # ____ tendrán mamografía positive y cancer. ____ tendrán mamografía positive y no cancer.
  # Por lo tanto, ____ de cada ____ tendrán cancer.

seq_guided <- "____ tendrán mamografía positiva y cáncer. ____ tendrán mamografía positive y no cancer.\nPor lo tanto, ____ de cada ____ tendrán cancer."

# dataframe with response types

response_types <- tibble("Response_type" = c("global_systematic", "global_intuitive", "sequential_simple", "sequential_guided"),
       "Response"= c(glob_systematic, glob_intuitive, seq_simple, seq_guided))
```

# Combine problem with questions
```{r}
for (i in 1:nrow(response_types)){
  
  cat(paste0(item_xxx,  "\n", response_types[i,2],  "\n\n\n"))

  }
```
































